services:
  web:
    restart: always
    build:
      dockerfile: ./build/web/Dockerfile
      context: .
    environment:
      - PORTFOLIO_BLOG_SECRET_KEY=$PORTFOLIO_BLOG_SECRET_KEY
      - PORTFOLIO_BLOG_DEBUG=$PORTFOLIO_BLOG_DEBUG
    expose:
      - 8000 # export django serving port to the service network
    ports:
      - "0.0.0.0:8001:8000" # map local port 8001 to the services port 80
    develop:
      watch:
        - action: sync
          path: ./web
          target: /root/app/

        - action: rebuild
          path: ./build/web/requirments.txt
