# Generated by Django 4.1.7 on 2026-04-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="date_created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
